name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Create .env.production.local
        run: echo "${{ secrets.DOTENV }}" > .env.production.local
      - name: Setup tools
        uses: jdx/mise-action@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Upload build files
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          target: ${{ secrets.SCP_TARGET }}
          source: dist/**
          strip_components: 1
          rm: true
